var enums={
	userStatusOptions:{
		REGISTERED_USER_STATUS:"R",
		CONFIRMED_USER_STATUS:"C",
		PAYING_USER_STATUS:"P"
	},
	userTypeOptions:{
		CUSTOMER_USER_TYPE:"C",
		BARBER_USER_TYPE:"B",
		HAIRSTYLIST_USER_TYPE:"H",
		HAIRDRESSER_USER_TYPE:"D",
		COSMETOLOGIST_USER_TYPE:"H",
		MANAGER_USER_TYPE:"M",	
	},
	appointmentStatusOptions:{
		REQUESTED_APPOINTMENT_STATUS:"R",
		CONFIRMED_APPOINTMENT_STATUS:"C",
		DENIED_APPOINTMENT_STATUS:"D",
		MADE_APPOINTMENT_STATUS:"M",
		CANCELLED_APPOINTMENT_STATUS:"N"
	},
	appointmentCustomerStatusOptions:{
		NEW_CUSTOMER:"N",
		EXISTING_CUSTOMER:"E",
	},
	scheduleTypeOptions:{
		HOURS:"H",
		CLOSED:"C"
	},
	shopCategoryOptions:{
			BARBERSHOP:"B",
			SALON:"S"
	},
	shopTypeOptions:{
		MAN_SALON:"M",
		BEAUTY_SALON:"S",
		HAIR_SALON:"H",
		NAIL_SALON:"N",
		HAIR_NAIL_SALON:"HNS"
	},
	shopClienteleGenderOptions:{
		MEN:"M",
		WOMEN:"W",
		EVERYBODY:"E"
	},
	hairTypeOptions:{		
		STRAIGHT:"S",
		WAVY:"W",
		COILED:"C",
		KINKY:"K"	
	},
	hairTextureOptions:{		
		STRAIGHT:"S",
		CURLY:"C"		
	},
	activity:{
		appointment:{
			REQUESTED:"AR",
			CANCELLED:"AC",
			MADE:"AM"
		},
		customer:{
			JOINED:"CJ",

		},
		servicer:{
			JOINED:"SJ"
		}
	},
	notification:{
		APPOINTMENT_REQUESTED:"NAR",
		APPOINTMENT_CONFIRMED:"NAC",
		CANCEL_REQUESTED:"NAD",
		SERVICER_REGISTERED:"NSR",
		SERVICER_ADDED:"NSA",
		CUSTOMER_REGISTERED:"NCR",
	}

};

exports.enums = enums;